apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-yqce
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-orlw-tenant/rhtap-demo-app/hacbs-test-project-yqce@sha256:8b6f9bcb5261982f667073d8dbce1a60550691c89861cbbb5a000e118cd7a933
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
