apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yqce
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yqce
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-yqce
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yqce
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yqce
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-orlw-tenant/rhtap-demo-app/hacbs-test-project-yqce@sha256:edb96c8e7e2681b97dfd094c9ffeb3ef5ae254b1534e3bd623876d9ef94b7744
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
